### PR TITLE
Typedef

### PR DESCRIPTION
**Pull request by marycpriyanka**
Created typedef and added some default values to numbers in Game model.  Since a typedef is already in develop, it will have merging conflict. You can overwrite the typedef in develop with the contents of this typedef after reviewing.

### CODE REVIEW

**Review by aditore — CHANGES_REQUESTED** [review]
Within typeDefs the createUser a needs to be through Auth not User

Also you can create a login mutation as well through Auth

**Comment by marycpriyanka** [comment]
Thank you for catching that! Now corrected.

**Comment by aditore** [comment]
Okay turns out I can't so I'll have to get to my computer after work!

**Review by aditore — APPROVED** [review]
We can add a me query in a different commit! but this all looks good!

**Pull request merged**
